[project]
name = "weather-gpt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Hariharan P R", email = "prhariharan2005@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
weather-gpt = "weather_gpt:main"

[build-system]
requires = ["uv_build>=0.12.4,<0.13.0"]
build-backend = "uv_build"
